# This is a basic workflow to help you get started with Actions

name: YouTube Shorts Upload

# Controls when the workflow will run
on:
  workflow_dispatch:
  # Scheduled YouTube upload jobs
#  schedule:
 #   - cron: "30 2 * * *"   # 8:00 AM IST  (02:30 UTC)
#    - cron: "30 7 * * *"   # 1:00 PM IST  (07:30 UTC)
#    - cron: "30 12 * * *"  # 6:00 PM IST  (12:30 UTC)
#    - cron: "30 15 * * *"  # 9:00 PM IST  (15:30 UTC)


jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      CONFIG: ${{ secrets.CONFIG }} # your rclone config contents as a secret

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Runs a set of commands using the runners shell
      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: rclone setup and files
        run: |
          sudo apt update && sudo apt install ffmpeg
          mkdir -p ~/.config/rclone
          echo "$CONFIG" > ~/.config/rclone/rclone.conf
          export RCLONE_CONFIG=~/.config/rclone/rclone.conf
          mkdir -p ~/mnt/storage
          rclone copy gdrive:Youtube ~/mnt/storage --progress -vv
          cd ~/mnt/storage
          rclone copy gdrive:Videos/videos.zip . --progress -vv
          unzip -o videos.zip -d .
          pip install google-api-python-client google-auth-oauthlib google-auth requests
          python main.py --creds-dir ./creds --accounts ken --privacy-status public --one-per-account --upscale
          python main.py --creds-dir ./creds --accounts kunikazu --privacy-status public --one-per-account --upscale
          python main.py --creds-dir ./creds --accounts naman --privacy-status public --one-per-account --upscale
          rm -rf videos/*
          find .
          ls 
          rm videos.zip
          rclone copy ~/mnt/storage gdrive:Youtube --progress -vv
        env:
          CONFIG: ${{ secrets.CONFIG }}
          
